name: Android Build Workflow

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        type: choice
        options:
          - 'assembleRelease'
          - 'assembleRelease_unlua'
        default: 'assembleRelease'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: (cd Hydrogen && chmod +x gradlew)

      - name: Execute Gradle Command in Hydrogen Directory
        run: |
          if [ "${{ github.event.inputs.build_type }}" = "assembleRelease" ]; then
            (cd Hydrogen && ./gradlew app:assembleRelease)
          elif [ "${{ github.event.inputs.build_type }}" = "assembleRelease_unlua" ]; then
            (cd Hydrogen && ./gradlew app:assembleRelease_unlua)
          fi

      # 上传 assembleRelease 产物
      - name: Upload Release APK
        if: github.event.inputs.build_type == 'assembleRelease'
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: |
            Hydrogen/app/build/outputs/apk/release/*.apk
            Hydrogen/app/build/outputs/mapping/release/mapping.txt

      # 上传 assembleRelease_unlua 产物
      - name: Upload Rebuilt APK
        if: github.event.inputs.build_type == 'assembleRelease_unlua'
        uses: actions/upload-artifact@v4
        with:
          name: release-unlua-apk
          path: |
            Hydrogen/app/build/outputs/apk/release/*.apk
            Hydrogen/app/build/outputs/mapping/release/mapping.txt